config/routes.rb
Rails.application.routes.draw do
  resources :urls, only: [:show, :create, :destroy]
  get 'r/:code', to: 'redirect#show'
  root 'urls#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hit.rb
class Hit < ApplicationRecord
  belongs_to :url
end

app/models/url.rb
class Url < ApplicationRecord
  before_create :create_code
  validates :url, presence: true, length: { minimum: 7, maximum: 255 }
  validates :code, allow_nil: true, length: { is: 5 }

  has_many :hits, dependent: :destroy

  private
   def create_code
      self.code  = SecureRandom.urlsafe_base64(5)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/redirect_controller.rb
class RedirectController < ApplicationController
  def show
    url = Url.find_by(code: url_params)
    if url
      Hit.new(url: url).save()
      redirect_to url.url
    else
      render html: '404 URL not found', status: 404
    end
  end

  private
    def url_params
      params.require(:code)
    end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls/1
  # GET /urls/1.json
  def show
    @shortenUrl = request.base_url + '/r/' + @url.code
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:code, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/_footer.html.erb
<div class='footer'>
  <div class='footer__content'>© Acme Corporation</div>
</div>

app/views/layouts/_header.html.erb
<nav class='header'>
  <div class='header__content'><%= link_to 'Shorten URL', root_path %></div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShorterner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='layout'>
      <div class='layout__header'>
        <%= render "layouts/header" %>
      </div>
      <div class='layout__main'>
        <%= yield %>
      </div>
      <div class='layout__footer'>
        <%= render "layouts/footer" %>
      </div>
    </div>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url, local: true) do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Urls</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.code %></td>
        <td><%= url.url %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<div class='shorten-form'>
  <div class='shorten-form__content'>
    <div class='shorten-form__title'>Paste the URL to be shorten</div>
    <%= form_for(@url, :html => { class: 'shorten-form__form' } ) do |f| %>
      <%= f.text_field :url, class: 'shorten-form__input', placeholder: 'Enter url here...', required: true %>
      <%= f.submit "Shorten", class: 'shorten-form__button button button--primary' %>
    <% end %>
    <div class='shorten-form__error'><%= @url.errors.any? ? 'Please provide a valid URL' : '' %></div>
  </div>
</div>

<div class='value-prop'>
  <div class='value-prop__item'>
    <div class='value-prop__title'>Easy to remember</div>
    <%= image_tag('remember.png', alt: '', class: 'value-prop__img') %>
    <div class='value-prop__desc'>Shorter urls are easier to share, tweet and email.</div>
  </div>
  <div class='value-prop__item'>
    <div class='value-prop__title'>Statistic</div>
    <%= image_tag('stats.png', alt: '', class: 'value-prop__img') %>
    <div class='value-prop__desc'>Track the impact of your campaigns.</div>
  </div>
</div>

app/views/urls/show.html.erb
<div class='url-details'>
  <div class='url-details__content'>
    <h2>URL</h2>
    <div class='url-details__url'>
      <input id='url-details__input' type='text' class='url-details__input' value='<%=  @shortenUrl %>' readonly>
      <button id='url-details__copy' class='url-details__copy button button--primary'>Copy</button>
    </div>
    <div class='url-details__item'>
      Original URL: <%= link_to @url.url, @url.url, target: '_blank' %>
    </div>
  </div>
</div>

<div class='stats'>
  <div class='stats__content'>
    <h2>Stats</h2>
    <div class='stats__items'>
      <div class='stats__item'>
        <div class='stats__header'>Total hits</div>
        <div class='stats__body'><%= @url.hits.count %></div>
        <div class='stats__footer'>Last week 0 hits</div>
      </div>

      <div class='stats__item'>
        <div class='stats__header'>Total users</div>
        <div class='stats__body'>0</div>
        <div class='stats__footer'>Last week 0 users</div>
      </div>

      <div class='stats__item'>
        <div class='stats__header'>Total invalid hits</div>
        <div class='stats__body'>0</div>
        <div class='stats__footer'>Last week 0 hits</div>
      </div>
    </div>
  </div>
</div>